// <auto-generated />
using CityBreaks.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityBreaks.Migrations
{
    [DbContext(typeof(CityBreaksContext))]
    [Migration("20250606021019_SeedInitialData")]
    partial class SeedInitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("CityBreaks.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("property_name");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_night");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Hotel Paulistano",
                            PricePerNight = 850.00m
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Pousada Cóe Velhote",
                            PricePerNight = 280.00m
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Name = "Hotel Copacabana",
                            PricePerNight = 1200.00m
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Name = "Apartamento em Take a Fire (Botafogo)",
                            PricePerNight = 450.00m
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            Name = "The Plaza Hotel",
                            PricePerNight = 2500.00m
                        },
                        new
                        {
                            Id = 6,
                            CityId = 4,
                            Name = "Brooklyn Apartment",
                            PricePerNight = 180.00m
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Name = "Hotel França",
                            PricePerNight = 1800.00m
                        },
                        new
                        {
                            Id = 8,
                            CityId = 7,
                            Name = "Apartamento Torre",
                            PricePerNight = 320.00m
                        },
                        new
                        {
                            Id = 9,
                            CityId = 9,
                            Name = "Hotel de Italia",
                            PricePerNight = 1100.00m
                        },
                        new
                        {
                            Id = 10,
                            CityId = 9,
                            Name = "B&B Centro Histórico",
                            PricePerNight = 150.00m
                        },
                        new
                        {
                            Id = 11,
                            CityId = 12,
                            Name = "Hotel Casa Fuster",
                            PricePerNight = 480.00m
                        },
                        new
                        {
                            Id = 12,
                            CityId = 12,
                            Name = "Apartamento Sagrada Família",
                            PricePerNight = 95.00m
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("city_name");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "São Paulo"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            Name = "Salvador"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 2,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            Name = "Miami"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 3,
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 3,
                            Name = "Nice"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 4,
                            Name = "Roma"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 4,
                            Name = "Milão"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 5,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 5,
                            Name = "Barcelona"
                        });
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "BR",
                            CountryName = "Brasil"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "US",
                            CountryName = "Estados Unidos"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "FR",
                            CountryName = "França"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "IT",
                            CountryName = "Itália"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "ES",
                            CountryName = "Espanha"
                        });
                });

            modelBuilder.Entity("CityBreaks.Models.Property", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.City", "City")
                        .WithMany("Properties")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.HasOne("CityBreaks.Web.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.City", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("CityBreaks.Web.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
